# django-graph
python manage.py migrate --run-syncdb

https://stackoverflow.com/questions/34548768/django-no-such-table-exception
